### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by ericdill** [ericdill/depfinder#63]
```
$ pipx install depfinder
  installed package depfinder 2.7.0, Python 3.8.3
  These apps are now globally available
    - depfinder
done! ✨ 🌟 ✨
$ depfinder .
Traceback (most recent call last):
  File "/home/ericdill/.local/bin/depfinder", line 5, in <module>
    from depfinder.cli import cli
  File "/home/ericdill/.local/pipx/venvs/depfinder/lib/python3.8/site-packages/depfinder/__init__.py", line 34, in <module>
    from .inspection import parse_file
  File "/home/ericdill/.local/pipx/venvs/depfinder/lib/python3.8/site-packages/depfinder/inspection.py", line 41, in <module>
    from .utils import AST_QUESTIONABLE, namespace_packages, SKETCHY_TYPES_TABLE
  File "/home/ericdill/.local/pipx/venvs/depfinder/lib/python3.8/site-packages/depfinder/utils.py", line 43, in <module>
    Loader=yaml.CSafeLoader,
AttributeError: module 'yaml' has no attribute 'CSafeLoader'
```

**Comment by CJ-Wright** [comment]
What version of pyyaml do you have locally?

**Comment by ericdill** [comment]
pyyaml from pip doesn't have CSafeLoader: https://pyyaml.org/wiki/PyYAMLDocumentation
